name: "productcatalogservice"

image:
  name: "gcr.io/google-samples/microservices-demo/productcatalogservice" 
  tag: "v0.2.4"
  containerPort: 3550

service:
  ports: 
  - name: grpc
    port: 3550
    targetPort: 3550

env:
- name: PORT
  value: "3550"