name: "recommendationservice"

image:
  name: "gcr.io/google-samples/microservices-demo/recommendationservice" 
  tag: "v0.2.4"

service:
  ports: 
  - name: grpc
    port: 8080
    targetPort: 8080

env:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"