global:
  name: "emailservice"
  environment: {}

deployment:
  image:
    name: ""
    tag: ""
  environment: {}
  readinessProbe: 
    periodSeconds: 5
    exec:
      command: ["/bin/grpc_health_probe", "-addr=:8080"]
  livenessProbe:
    periodSeconds: 5
    exec:
      command: ["/bin/grpc_health_probe", "-addr=:8080"]
  resources:
    limits:
      cpu: 2
      memory: 2000Mi
    requests:
      cpu: 500m
      memory: 500Mi

service:
  type: ClusterIP
  specs:
  - port: grpc
    targetPort: 5000
    name: 8080