kind: Pod
apiVersion: v1
metadata:
  name: signin-app
  labels:
    app: signin
spec:
  containers:
    - name: signin-app
      image: hashicorp/http-echo
      args:
        - "-text=signin"
---
kind: Service
apiVersion: v1
metadata:
  name: signin-service
spec:
  selector:
    app: signin
  ports:
    - port: 5678 # Default port for image
---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: platform-ingress-nginx
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - http:
#       paths:
#         - path: /signin
#           pathType: Prefix
#           backend:
#             service:
#               name: signin-service
#               port:
#                 number: 5678
---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: platform-ingress
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - http:
#       paths:
#         - path: /xcd
#           pathType: Prefix
#           backend:
#             service:
#               name: kong-xcd-kong-proxy
#               port:
#                 number: 80