# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: ingress-nginx
#   namespace: default
#   labels:
#     project: tools
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   project: default
#   source:
#     path: charts/ingress-nginx
#     repoURL: https://github.com/abork-dolby/k8-sandbox-k8.git
#     targetRevision: HEAD
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
