apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-controlplane
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    project: online-boutique
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: platform
  source:
    path: charts/istio-controlplane
    repoURL: https://github.com/abork-dolby/k8-sandbox-k8.git
    targetRevision: HEAD
  project: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true