apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: default
  labels:
    project: tools
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: charts/kong
    repoURL: https://github.com/abork-dolby/k8-sandbox-k8.git
    targetRevision: HEAD
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
