apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-xcd
  namespace: platform
  labels:
    project: tools
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: xcd
  project: xcd
  source:
    path: charts/kong
    repoURL: https://github.com/abork-dolby/k8-sandbox-k8.git
    targetRevision: HEAD
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-platform
  namespace: platform
  labels:
    project: tools
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  project: platform
  source:
    path: charts/kong
    repoURL: https://github.com/abork-dolby/k8-sandbox-k8.git
    targetRevision: HEAD
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
