apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: currencyservice
  namespace: default
  labels:
    project: online-boutique
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: platform
  source:
    path: charts/micro-service
    repoURL: https://github.com/abork-dolby/k8-sandbox-k8.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - "../../apps/values/currencyservice.values.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true