apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emailservice
  namespace: default
  labels:
    project: online-boutique
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: platform
  source:
    path: charts/micro-service-python
    repoURL: https://github.com/abork-dolby/k8-sandbox-k8.git
    targetRevision: HEAD
    helm:
      parameters:
      - name: name
        value: "emailservice"
      - name: image.name
        value: gcr.io/google-samples/microservices-demo/emailservice
      - name: image.tag
        value: v0.2.4
      - name: service.ports[0].port
        value: 5000
      - name: service.ports[0].name
        value: grpc
      - name: service.ports[0].targetPort
        name: 8080
  syncPolicy:
    automated:
      prune: true
      selfHeal: true