apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-ms
  namespace: platform
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  project: platform
  source:
    path: charts/microservice
    repoURL: https://github.com/abork-dolby/k8-sandbox-k8.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - "../../apps/values/hello.values.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true