apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recommendationservice
  namespace: default
  labels:
    project: online-boutique
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: platform
  source:
    path: charts/micro-service-python
    repoURL: https://github.com/abork-dolby/k8-sandbox-k8.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true