name: ""

image:
  name: "" 
  tag: "latest"
  containerPort: 8080

service:
  ports: 
  - name: grpc
    port: 5000
    targetPort: 8080

env:
- name: PORT
  value: "8080"
- name: DISABLE_PROFILER
  value: "1"