apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: {{ .Values.image.name }} : {{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        {{- if (merge .Values.global.environment .Values.environment) }}
        env:
        {{- range $name, $value := merge .Values.global.environment .Values.environment}}
        - name: {{ $name | quote}}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi