apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: {{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        {{- if .Values.deployment.environment}}
        env:
        {{- range $name, $value := .Values.deployment.environment }}
        - name: {{ $name | quote}}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        readinessProbe:
          periodSeconds: 5
          exec:
            command: 
              {{- range $command := .Values.deployment.readinessProbe.execCommand }}
              - {{ $command }}
              {{- end}}
        livenessProbe:
          periodSeconds: 5
          exec:
            command: 
              {{- range $command := .Values.deployment.livenessProbe.execCommand }}
              - {{ $command }}
              {{- end}}
        resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}