apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.global.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      replicas: 2
      containers:
      - name: server
        image: {{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
        ports:
        - containerPort: 8080
        {{- if .Values.deployment.environment}}
        env:
        {{- range $name, $value := .Values.deployment.environment }}
        - name: {{ $name | quote}}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}