apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.global.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.global.name }}
  ports:
  {{- toYaml .Values.service.ports | nindent 2 }}