microservices:
  - name: emailservice
    env: dev
    namespace: default
    helmParameters:
    - name: "global.name"
      value: "emailservice"
    - name: "deployment.image.name"
      value: "gcr.io/google-samples/microservices-demo/emailservice"
    - name: "deployment.image.tag"
      value: "v0.2.4"