kong:
  env:
    prefix: /kong_prefix/
    database: "off"
  
  proxy:
    type: NodePort
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    ## targetCPUUtilizationPercentage only used if the cluster doesn't support autoscaling/v2beta
    ## targetCPUUtilizationPercentage:
    ## Otherwise for clusters that do support autoscaling/v2beta, use metrics
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80