apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
  ports:
  - name: {{ .Values.name }}
    protocol: TCP
    port: 3000