apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: xcd
  namespace: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: xCD services
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the xCD namespace in the same cluster
  destinations:
  - namespace: xcd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  syncWindows:
  - kind: allow
    schedule: '10 1 * * *'
    duration: 1h
    applications:
    - '*-prod'
    manualSync: true
    namespaces:
    - xcd