apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Platform services
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the platform namespace in the same cluster
  destinations:
  - namespace: platform
    server: https://kubernetes.default.svc
  # syncWindows:
  # - kind: allow
  #   schedule: '10 1 * * *'
  #   duration: 1h
  #   applications:
  #   - '*-prod'
  #   manualSync: true
  #   namespaces:
  #   - platform