# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: xcd
#   namespace: default
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   description: Space for all services and tools for xCD app
#   # Allow manifests to deploy from any Git repos
#   sourceRepos:
#   - '*'
#   # Only permit applications to deploy to the guestbook namespace in the same cluster
#   destinations:
#   - namespace: xcd
#     server: https://kubernetes.default.svc