apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
  {{- toYaml .Values.service.ports | nindent 2 }}
{{- if .Values.service.isPublic }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-external
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.name }}
  ports:
  {{- toYaml .Values.service.ports | nindent 2 }}
{{- end}}